// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/compilador/lexer/Lexer.flex

/* =========================================================================
 *  Lexer.flex  —  Especificación JFlex para el DSL de Topologías de Red
 *
 *  Para generar Lexico.java ejecutar:
 *      java -jar lib/jflex-full-1.9.1.jar src/compilador/lexer/Lexer.flex -d src/compilador/lexer/
 *
 *  La clase generada se llama Lexico y su método principal es yylex().
 *  Cada llamada a yylex() devuelve el siguiente Token o null al llegar al EOF.
 * ========================================================================= */

package compilador.lexer;

import compilador.errors.CompilerError;
import compilador.errors.ErrorType;
import java.util.ArrayList;
import java.util.List;


@SuppressWarnings("fallthrough")
public class Lexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\6\0"+
    "\1\4\5\0\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\4\16\1\0\1\17\2\0\1\20"+
    "\2\0\13\21\1\22\16\21\4\0\1\23\1\0\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\21\1\32\1\33"+
    "\2\21\1\34\1\35\1\36\1\37\1\40\1\21\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\2\21\1\47\1\50"+
    "\1\0\1\51\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\4\1\1\4\15\5"+
    "\1\6\1\7\1\10\4\0\10\5\1\11\6\5\4\0"+
    "\1\5\1\12\6\5\1\13\4\5\1\14\2\0\12\5"+
    "\1\15\4\0\12\5\2\0\6\5\1\16\1\17\1\20"+
    "\1\21\1\22\4\0\7\5\2\0\1\5\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\3\31\2\5\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\52\0\322\0\374"+
    "\0\u0126\0\u0150\0\52\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222"+
    "\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372"+
    "\0\52\0\52\0\52\0\u039c\0\u0150\0\u03c6\0\322\0\u03f0"+
    "\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec\0\u0516\0\u017a"+
    "\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666"+
    "\0\u0690\0\u06ba\0\u06e4\0\u017a\0\u070e\0\u0738\0\u0762\0\u078c"+
    "\0\u07b6\0\u07e0\0\u017a\0\u080a\0\u0834\0\u085e\0\u0888\0\u017a"+
    "\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a\0\u0984\0\u09ae\0\u09d8"+
    "\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u017a\0\u0aaa\0\u0ad4\0\u0afe"+
    "\0\u0b28\0\u0b52\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\u0c24\0\u0c4e"+
    "\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e"+
    "\0\u0dc8\0\u0df2\0\u0e1c\0\u017a\0\u017a\0\u017a\0\u017a\0\u0e46"+
    "\0\u0e70\0\u0e9a\0\u0ec4\0\u0eee\0\u0f18\0\u0f42\0\u0f6c\0\u0f96"+
    "\0\u0fc0\0\u0fea\0\u1014\0\u103e\0\u1068\0\u1092\0\u017a\0\u017a"+
    "\0\u017a\0\u017a\0\u017a\0\u017a\0\52\0\u10bc\0\u10e6\0\u1110"+
    "\0\u113a\0\u017a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\2\1\7"+
    "\1\10\1\11\4\12\1\13\1\2\2\14\1\2\1\15"+
    "\1\14\1\16\1\17\1\14\1\20\1\14\1\21\1\22"+
    "\1\23\2\14\1\24\1\25\1\26\1\27\2\14\1\30"+
    "\1\14\1\31\1\32\53\0\2\3\47\0\2\4\1\0"+
    "\47\4\20\0\1\33\37\0\1\34\51\0\1\34\1\0"+
    "\7\35\41\0\1\34\1\0\5\35\1\36\1\37\41\0"+
    "\1\34\1\0\7\37\40\0\1\14\1\0\10\14\2\0"+
    "\27\14\7\0\1\14\1\0\10\14\2\0\5\14\1\40"+
    "\11\14\1\41\7\14\7\0\1\14\1\0\10\14\2\0"+
    "\16\14\1\42\10\14\7\0\1\14\1\0\10\14\2\0"+
    "\3\14\1\43\23\14\7\0\1\14\1\0\10\14\2\0"+
    "\12\14\1\44\14\14\7\0\1\14\1\0\10\14\2\0"+
    "\15\14\1\45\11\14\7\0\1\14\1\0\10\14\2\0"+
    "\3\14\1\46\23\14\7\0\1\14\1\0\10\14\2\0"+
    "\16\14\1\47\10\14\7\0\1\14\1\0\10\14\2\0"+
    "\5\14\1\50\21\14\7\0\1\14\1\0\10\14\2\0"+
    "\7\14\1\51\6\14\1\52\10\14\7\0\1\14\1\0"+
    "\10\14\2\0\7\14\1\53\15\14\1\54\1\14\7\0"+
    "\1\14\1\0\10\14\2\0\12\14\1\55\14\14\7\0"+
    "\1\14\1\0\10\14\2\0\7\14\1\56\17\14\12\0"+
    "\1\57\1\60\1\61\4\62\41\0\1\34\1\0\6\37"+
    "\41\0\1\14\1\0\10\14\2\0\5\14\1\63\21\14"+
    "\7\0\1\14\1\0\10\14\2\0\17\14\1\64\7\14"+
    "\7\0\1\14\1\0\10\14\2\0\15\14\1\65\11\14"+
    "\7\0\1\14\1\0\10\14\2\0\22\14\1\66\4\14"+
    "\7\0\1\14\1\0\10\14\2\0\20\14\1\67\6\14"+
    "\7\0\1\14\1\0\10\14\2\0\22\14\1\70\4\14"+
    "\7\0\1\14\1\0\10\14\2\0\17\14\1\71\7\14"+
    "\7\0\1\14\1\0\10\14\2\0\4\14\1\72\22\14"+
    "\7\0\1\14\1\0\10\14\2\0\6\14\1\73\20\14"+
    "\7\0\1\14\1\0\10\14\2\0\23\14\1\74\3\14"+
    "\7\0\1\14\1\0\10\14\2\0\20\14\1\75\6\14"+
    "\7\0\1\14\1\0\10\14\2\0\12\14\1\76\14\14"+
    "\7\0\1\14\1\0\10\14\2\0\17\14\1\77\7\14"+
    "\7\0\1\14\1\0\10\14\2\0\4\14\1\100\22\14"+
    "\10\0\1\101\51\0\1\101\1\0\7\62\41\0\1\101"+
    "\1\0\5\62\1\102\1\57\41\0\1\101\1\0\7\57"+
    "\40\0\1\14\1\0\10\14\2\0\7\14\1\103\17\14"+
    "\7\0\1\14\1\0\10\14\2\0\7\14\1\104\17\14"+
    "\7\0\1\14\1\0\10\14\2\0\3\14\1\105\23\14"+
    "\7\0\1\14\1\0\10\14\2\0\7\14\1\106\17\14"+
    "\7\0\1\14\1\0\10\14\2\0\7\14\1\107\17\14"+
    "\7\0\1\14\1\0\10\14\2\0\22\14\1\110\4\14"+
    "\7\0\1\14\1\0\10\14\2\0\12\14\1\111\14\14"+
    "\7\0\1\14\1\0\10\14\2\0\22\14\1\112\4\14"+
    "\7\0\1\14\1\0\10\14\2\0\24\14\1\113\2\14"+
    "\7\0\1\14\1\0\10\14\2\0\22\14\1\114\4\14"+
    "\7\0\1\14\1\0\10\14\2\0\16\14\1\115\10\14"+
    "\12\0\1\116\1\117\1\120\4\121\41\0\1\101\1\0"+
    "\6\57\41\0\1\14\1\0\10\14\2\0\21\14\1\122"+
    "\5\14\7\0\1\14\1\0\10\14\2\0\5\14\1\123"+
    "\21\14\7\0\1\14\1\0\10\14\2\0\4\14\1\124"+
    "\22\14\7\0\1\14\1\0\10\14\2\0\25\14\1\125"+
    "\1\14\7\0\1\14\1\0\10\14\2\0\20\14\1\126"+
    "\6\14\7\0\1\14\1\0\10\14\2\0\16\14\1\127"+
    "\10\14\7\0\1\14\1\0\10\14\2\0\13\14\1\130"+
    "\13\14\7\0\1\14\1\0\10\14\2\0\7\14\1\131"+
    "\17\14\7\0\1\14\1\0\10\14\2\0\7\14\1\132"+
    "\17\14\7\0\1\14\1\0\10\14\2\0\5\14\1\133"+
    "\21\14\10\0\1\134\51\0\1\134\1\0\7\121\41\0"+
    "\1\134\1\0\5\121\1\135\1\116\41\0\1\134\1\0"+
    "\7\116\40\0\1\14\1\0\10\14\2\0\21\14\1\136"+
    "\5\14\7\0\1\14\1\0\10\14\2\0\22\14\1\137"+
    "\4\14\7\0\1\14\1\0\10\14\2\0\3\14\1\140"+
    "\23\14\7\0\1\14\1\0\10\14\2\0\3\14\1\141"+
    "\23\14\7\0\1\14\1\0\10\14\2\0\10\14\1\142"+
    "\4\14\1\143\11\14\7\0\1\14\1\0\10\14\2\0"+
    "\17\14\1\144\7\14\7\0\1\14\1\0\10\14\2\0"+
    "\7\14\1\145\17\14\7\0\1\14\1\0\10\14\2\0"+
    "\20\14\1\146\6\14\7\0\1\14\1\0\10\14\2\0"+
    "\20\14\1\147\6\14\7\0\1\14\1\0\10\14\2\0"+
    "\11\14\1\150\15\14\12\0\1\151\1\152\1\153\4\154"+
    "\41\0\1\134\1\0\6\116\41\0\1\14\1\0\10\14"+
    "\2\0\17\14\1\155\7\14\7\0\1\14\1\0\10\14"+
    "\2\0\3\14\1\156\23\14\7\0\1\14\1\0\10\14"+
    "\2\0\21\14\1\157\5\14\7\0\1\14\1\0\10\14"+
    "\2\0\13\14\1\160\13\14\7\0\1\14\1\0\10\14"+
    "\2\0\3\14\1\161\23\14\7\0\1\14\1\0\10\14"+
    "\2\0\7\14\1\162\17\14\7\0\1\14\1\0\10\14"+
    "\2\0\1\14\1\163\25\14\11\0\1\164\51\0\1\164"+
    "\7\154\42\0\1\164\5\154\1\165\1\151\42\0\1\164"+
    "\7\151\40\0\1\14\1\0\10\14\2\0\16\14\1\166"+
    "\10\14\7\0\1\14\1\0\10\14\2\0\20\14\1\167"+
    "\6\14\7\0\1\14\1\0\10\14\2\0\7\14\1\170"+
    "\17\14\7\0\1\14\1\0\10\14\2\0\13\14\1\171"+
    "\13\14\7\0\1\14\1\0\10\14\2\0\26\14\1\172"+
    "\7\0\1\14\1\0\10\14\2\0\22\14\1\173\4\14"+
    "\7\0\1\14\1\0\4\14\1\174\3\14\2\0\27\14"+
    "\12\0\1\175\2\176\1\177\3\175\42\0\1\164\6\151"+
    "\41\0\1\14\1\0\10\14\2\0\12\14\1\200\14\14"+
    "\12\0\7\175\43\0\3\175\44\0\1\14\1\0\10\14"+
    "\2\0\15\14\1\201\11\14\7\0\1\14\1\0\10\14"+
    "\2\0\22\14\1\202\4\14\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4452];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\4\1\1\11\15\1\3\11"+
    "\4\0\17\1\4\0\16\1\2\0\13\1\4\0\12\1"+
    "\2\0\13\1\4\0\7\1\2\0\7\1\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /** Lista donde se acumulan los errores léxicos */
    private List<CompilerError> errors = new ArrayList<>();

    /** Acceso a la lista de errores desde el Main */
    public List<CompilerError> getErrors() { return errors; }

    /** Crea un Token con línea y columna correctas (1-indexed) */
    private Token tok(TokenType t, String v) {
        return new Token(t, v, yyline + 1, yycolumn + 1);
    }

    /** Registra un error léxico y devuelve un token ERROR */
    private Token lexError(String lexema) {
        String msg = "Carácter no reconocido: '" + lexema + "'";
        errors.add(new CompilerError(ErrorType.LEXICO, msg, yyline + 1, yycolumn + 1));
        return tok(TokenType.ERROR, lexema);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return lexError(yytext());
            }
          // fall through
          case 27: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 28: break;
          case 3:
            { return tok(TokenType.DOT,         yytext());
            }
          // fall through
          case 29: break;
          case 4:
            { return tok(TokenType.SEMICOLON,   yytext());
            }
          // fall through
          case 30: break;
          case 5:
            { return tok(TokenType.ID,          yytext());
            }
          // fall through
          case 31: break;
          case 6:
            { return tok(TokenType.LBRACE,      yytext());
            }
          // fall through
          case 32: break;
          case 7:
            { return tok(TokenType.RBRACE,      yytext());
            }
          // fall through
          case 33: break;
          case 8:
            { return tok(TokenType.ARROW,       yytext());
            }
          // fall through
          case 34: break;
          case 9:
            { return tok(TokenType.PC,          yytext());
            }
          // fall through
          case 35: break;
          case 10:
            { return tok(TokenType.APP,         yytext());
            }
          // fall through
          case 36: break;
          case 11:
            { return tok(TokenType.RED,         yytext());
            }
          // fall through
          case 37: break;
          case 12:
            { return tok(TokenType.WEB,         yytext());
            }
          // fall through
          case 38: break;
          case 13:
            { return tok(TokenType.TIPO,        yytext());
            }
          // fall through
          case 39: break;
          case 14:
            { return tok(TokenType.LAPTOP,      yytext());
            }
          // fall through
          case 40: break;
          case 15:
            { return tok(TokenType.MOBILE,      yytext());
            }
          // fall through
          case 41: break;
          case 16:
            { return tok(TokenType.ROUTER,      yytext());
            }
          // fall through
          case 42: break;
          case 17:
            { return tok(TokenType.SERVER,      yytext());
            }
          // fall through
          case 43: break;
          case 18:
            { return tok(TokenType.SWITCH,      yytext());
            }
          // fall through
          case 44: break;
          case 19:
            { return tok(TokenType.CONECTAR,    yytext());
            }
          // fall through
          case 45: break;
          case 20:
            { return tok(TokenType.DATABASE,    yytext());
            }
          // fall through
          case 46: break;
          case 21:
            { return tok(TokenType.FIREWALL,    yytext());
            }
          // fall through
          case 47: break;
          case 22:
            { return tok(TokenType.INTERFAZ,    yytext());
            }
          // fall through
          case 48: break;
          case 23:
            { return tok(TokenType.INTERNET,    yytext());
            }
          // fall through
          case 49: break;
          case 24:
            { return tok(TokenType.SWITCHL3,    yytext());
            }
          // fall through
          case 50: break;
          case 25:
            { return tok(TokenType.IP_ADDRESS,  yytext());
            }
          // fall through
          case 51: break;
          case 26:
            { return tok(TokenType.ACCESSPOINT, yytext());
            }
          // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
