
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SWITCHL3 = 5;
  public static final int SEMICOLON = 23;
  public static final int RBRACE = 22;
  public static final int SERVER = 7;
  public static final int CONECTAR = 14;
  public static final int WEB = 16;
  public static final int INTERNET = 12;
  public static final int SWITCH = 6;
  public static final int INTERFAZ = 13;
  public static final int LBRACE = 21;
  public static final int ID = 19;
  public static final int FIREWALL = 4;
  public static final int RED = 2;
  public static final int TIPO = 15;
  public static final int APP = 18;
  public static final int ROUTER = 3;
  public static final int EOF = 0;
  public static final int IP_ADDRESS = 20;
  public static final int DATABASE = 17;
  public static final int MOBILE = 10;
  public static final int DOT = 25;
  public static final int ARROW = 24;
  public static final int error = 1;
  public static final int PC = 8;
  public static final int LAPTOP = 9;
  public static final int ACCESSPOINT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RED",
  "ROUTER",
  "FIREWALL",
  "SWITCHL3",
  "SWITCH",
  "SERVER",
  "PC",
  "LAPTOP",
  "MOBILE",
  "ACCESSPOINT",
  "INTERNET",
  "INTERFAZ",
  "CONECTAR",
  "TIPO",
  "WEB",
  "DATABASE",
  "APP",
  "ID",
  "IP_ADDRESS",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "ARROW",
  "DOT"
  };
}

