
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SWITCHL3 = 6;
  public static final int PUNTO = 21;
  public static final int PYC = 24;
  public static final int SERVER = 7;
  public static final int CONECTAR = 15;
  public static final int IP_KW = 14;
  public static final int WEB = 17;
  public static final int INTERNET = 12;
  public static final int FLECHA = 20;
  public static final int SWITCH = 5;
  public static final int INTERFAZ = 13;
  public static final int FIREWALL = 4;
  public static final int RED = 2;
  public static final int DIRECCION_IP = 25;
  public static final int TIPO = 16;
  public static final int APP = 19;
  public static final int ROUTER = 3;
  public static final int EOF = 0;
  public static final int DATABASE = 18;
  public static final int MOBILE = 10;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 26;
  public static final int LLAVE_C = 23;
  public static final int LLAVE_A = 22;
  public static final int PC = 8;
  public static final int LAPTOP = 9;
  public static final int ACCESSPOINT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RED",
  "ROUTER",
  "FIREWALL",
  "SWITCH",
  "SWITCHL3",
  "SERVER",
  "PC",
  "LAPTOP",
  "MOBILE",
  "ACCESSPOINT",
  "INTERNET",
  "INTERFAZ",
  "IP_KW",
  "CONECTAR",
  "TIPO",
  "WEB",
  "DATABASE",
  "APP",
  "FLECHA",
  "PUNTO",
  "LLAVE_A",
  "LLAVE_C",
  "PYC",
  "DIRECCION_IP",
  "IDENTIFICADOR"
  };
}

